name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Check
        run: |
          echo ${{github.event_name}}
          echo ${{github.ref}}
          echo ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-page
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _static/
          force_orphan: true


#         github_token: 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
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@4.1.0
#       with:
#         branch: gh-page
#         folder: _build
